export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const PACKAGES_LOADING = 'PACKAGES_LOADING';
export const ADD_PACKAGES = 'ADD_PACKAGES';
export const PACKAGES_FAILED = 'PACKAGES_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';

export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 
